version: "2"

services:
  mysqldb:
    image: 'mysql:latest'
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
  projetdevopsback:
    
    depends_on:
      - mysqldb
    image: ferielhakim/projetdevopsback
    container_name: projetdevopsback  
    build: .
    restart: on-failure
    ports:
      - '8089:8089'
   
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tpachato?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: